apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/xoxxxoox/argoCD.git
    targetRevision: main
    path: stock-city/helm-chart
    helm:
      valueFiles:
      - values.yaml
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true  
    syncOptions:
    - CreateNamespace=true
