apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
  # Add a this finalizer ONLY if you want these to cascade delete.

spec:
  project: stock-city
  
  source:
    repoURL: https://github.com/xoxxxoox/argoCD.git
    targetRevision: HEAD            # HEAD는 소스 리포지토리의 가장 최신 리비전, 보통 main 브랜치
    path: stock-city
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: default
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true