apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: stock-city
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/xoxxxoox/argoCD.git
    targetRevision: main
    path: stock-city/
    helm:
      valueFiles:
      - my-values.yaml
  
  destination
    namespace: default
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true