apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  labels:
    app.kubernetes.io/name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
{{- range .Values.externalDNS.clusterRoleBinding.subjects }}
  - kind: ServiceAccount
    name: {{ .serviceAccount }}
    namespace: {{ .namespace }}
{{- end }}